### ISSUE TITLE
First time Setup Error in AWS account

### ISSUE THREAD

**Issue by KeshavReddy08** [aws-samples/eks-workshop-v2#339]
Error while installing hashicorp/time v0.9.1: mkdir .terraform/providers/registry.terraform.io/hashicorp/time: no space left on device

Facing Errors after the Terraform init command .

please let me know how can i fix this

**Comment by niallthomson** [comment]
Hi @KeshavReddy08 can you provide the output of this command from Cloud9:

```
df -h
```

**Comment by jaradtke-aws** [comment]
@KeshavReddy08 - if the space is consumed on your Cloud9 instance (and you have investigated that there is an acceptable reason for the consumption), there is a procedure from the EKSWorkShop (now archived as it has been replaced by the new Workshop) which will expand your disk - check out the very bottom of the page.
https://archive.eksworkshop.com/020_prerequisites/workspace/

**Comment by niallthomson** [comment]
Yes it sounds like you're running the Terraform on your own Cloud9 instance and its run out of disk space. The Terraform can be run from your local machine since we set up a Cloud9 instance for you to use with all tools pre-installed and the disk already expanded per the process @jaradtke-aws mentioned.

**Comment by ROunofF** [comment]
Environment error.
