### ISSUE TITLE
Remove the IAM user needed for this workshop

### ISSUE THREAD

**Issue by Chandrian** [aws-samples/eks-workshop-v2#384]
### What would you like to be added?

Not a bug request, not a security concerned so I guess I'll just put it here as it's not per say something to be added, but mostly something to be removed (or changed).

A lot (if not most) companies are using SAML and IdPs to connect to their accounts and don't have access or permissions to create IAM users for security reasons (controlled by SCPs). Just because of GitOps, this workshop can't be deployed as it's been set up to create an IAM user GitOps. 
Could we please remove that dependency? It looks like a great workshop, but if we cannot build it it's worthless....
a) Could we switch GitOps to assume a role instead of using an IAM user (or a cert)
b) If GitOps does not support anything else, could it be an optional install so that we could check out all the other stuff?

Thank you!

### Why is this needed?

It is needed to let more people use the workshop

**Comment by niallthomson** [comment]
Hi @Chandrian thanks for the feedback, this is useful. As far as I'm aware the Flux GitOps flow requires an IAM user due to how SSH keys are associated but we are currently working on some re-organization which I believe will help address the overarching problem. The intended design will break apart the Terraform so its more modular and directly related to each lab. That means if you don't have permissions to create an IAM user you will still be able to execute the rest of the labs.

**Comment by niallthomson** [comment]
The new workshop structure that we just published now removes this IAM user from being created initially. All other labs should be accessible.

**Comment by niallthomson** [comment]
Closing this issue based on the above
