### ISSUE TITLE
[Bug]: Installation Error: Unsupported Terraform Core version (v1.4)

### ISSUE THREAD

**Issue by jtanton** [aws-samples/eks-workshop-v2#394]
### Installation method

Own AWS account

### What happened?

New minor issue.  I am now on ubuntu (WSL) and my Terraform version is 1.4.  The required version statement won't let me leave version 1.3.x so I have to change the TF code.  Should I do a pull request to fix this or can you update the TF in the repo?
│ Error: Unsupported Terraform Core version
│
│   on **modules/ide/main.tf** line 10, in terraform:
│   10:   required_version = "~> 1.3.7" (edited) 

[1:06](https://amzn-aws.slack.com/archives/D04T5MVC00M/p1678395963253409)
on main.tf line 9, in terraform:
│    9:   required_version = "~> 1.3.7"
[1:06](https://amzn-aws.slack.com/archives/D04T5MVC00M/p1678395964653629)
on **modules/cluster/providers.tf** line 43, in terraform:
│   43:   required_version = "~> 1.3.7"

### What did you expect to happen?

I expected Terraform Version 1.37 + to work per documetation.  I am running V1.4

### How can we reproduce it?

Yes

### Anything else we need to know?

I removed the tilde ~ in my local files and now INIT is running.

### EKS version

lab default version

**Comment by bryantbiggs** [comment]
the `~>` pattern will allow the rightmost version to "float" and automatically update to the latest version available. The current form allows for versions `1.3.7`, `1.3.8`, etc. up to, but not including, `1.4.0` (can achieve same outcome using the pattern `">= 1.3.7, <1.4.0"`. The fix here would be to remove the patch restriction (i.e. - `"~> 1.3"`); this is preferred over the `>= 1.3.7` form because this form would allow something like `2.0` if that were to be released in the future

**Comment by niallthomson** [comment]
This will have been resolved by the new workshop structure just published since we pin the TF CLI version installed in Cloud9
