### ISSUE TITLE
Add Helm section, update labs to use Helm

### ISSUE THREAD

**Issue by candonov** [aws-samples/eks-workshop-v2#428]
Currently the workshop is using kustomize for installing the demo app. Kustomize works well for examples and getting started but is not scalable for production. One concern here is that because the workshop is using kustomize, customer might assume it is best practice and adopt the pattern for production. 

Change the workshop sample application installations to use helm.

Add a section explain what helm is, and different pattern of usage, here are some ideas:
- dependency charts, making one chart dependent on the other. Use case, you are using network policies and most off the shelf charts don't support them, you can create an in-house helm chart and make the off the shelf one dependent on it.
- how and when to use helm and kustomize together, i.e. post-render kustomize for helm charts you don't own: 
https://github.com/thomastaylor312/advanced-helm-demos/tree/master/post-render
https://helm.sh/docs/topics/advanced/#post-rendering

**Comment by svennam92** [comment]
Kustomize is suitable for production. We choose to use Kustomize for a number of reasons, primarily due to clarity in the YAML (for example, seeing which lines have changed when updating a deployment). That being said, I would be happy to introduce a section focusing on Helm. Can we open a [feat] request issue?
