### ISSUE TITLE
Instruction for "Setup in your AWS account" not clear about reference to Cloud9

### ISSUE THREAD

**Issue by arvind-v** [aws-samples/eks-workshop-v2#481]
### What would you like to be added?

Clarify that Cloud9 IDE in the setup instructions is referencing the eks-workshop Cloud9 environment.   

### Why is this needed?

"Setup in your AWS Account" refers to Cloud9, but it was not totally clear that it was referencing the eks-workshop Cloud9 IDE, which has all the prerequisite commands and environment variables setup. I tried running the lab instructions from a local copy of the repo I had cloned and after a few tries realized that the instructions provided work only when run inside of the eks-workshop Cloud9 environment.

**Comment by gvasels-aws** [comment]
will +1 this and would also call out that under https://www.eksworkshop.com/docs/introduction/ide- if you deploy into your own account (which also includes a fresh Cloud9 Instance), commands like aws eks describe-cluster --name $EKS_CLUSTER_NAME will not inherently work because EKS_CLUSTER_NAME is not set. You have to either create these environment variables or just replace $EKS_CLUSTER_NAME with the actual name of your cluster.
