### ISSUE TITLE
Shortcut to deploy all previous modules to allow user to participate it the Observability lab 

### ISSUE THREAD

**Issue by lyakhovv** [aws-samples/eks-workshop-v2#495]
### What would you like to be added?

Additional instruction to deploy modules from previous lab

### Why is this needed?

To help user to participate in the Observability Lab even if user did not complete previous lab or join late.

**Comment by lyakhovv** [comment]
I was delivering this workshop, and few customers arrived late and did not complete the initial task.  This small change, just provide customer with a shortcut to run the single command (vs reading the entire config session ) to deploy all the modules and participate in the Observability workshop.

**Comment by niallthomson** [comment]
The process executed by the `reset-environment` command include what was in your PR. This is meant to be executed at the start of each lab but it looks like a couple of observability labs are missing this (resource view and kubecost).

Instead of the change you submitted, you should ensure those labs mentioned above include this block:

https://github.com/aws-samples/eks-workshop-v2/blob/main/website/docs/observability/open-source-metrics/index.md?plain=1#L7-L14

**Comment by lyakhovv** [comment]
will do.

**Comment by niallthomson** [comment]
This was completed by #506
